name: Merge to store themes

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'templates/*.json'
      - 'config/*.json'
      - 'locales/*.json'
      - 'sections/*.json'
      - 'snippets/*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge-live
        with:
          github_token: ${{ github.token }}
          source: 'main'
          target: 'live/main'